description: Ya Like Jazz?
author: TryingToBehooman + TallYate
name: BeanMobs
version: 2.6
main: me.tallhooman.Main
api-version: 1.16

commands:
   extradifficulty:
      aliases:
      - ed
      description: changes the extra difficulty